"""create_initial_schema

Revision ID: 9352c0619374
Revises: 
Create Date: 2026-10-04 14:21:20.497385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9352c0619374'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('payload_snapshot', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('customers_blocklist',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_value', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_blocklist_entity_value'), ['entity_value'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_ref', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=32), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('card_bin', sa.String(length=8), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_card_fingerprint'), ['card_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_customer_email'), ['customer_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_razorpay_order_id'), ['razorpay_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_razorpay_payment_id'), ['razorpay_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_ref'), ['transaction_ref'], unique=True)

    op.create_table('reconciliation_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_status', sa.String(length=32), nullable=False),
    sa.Column('internal_decision', sa.String(length=16), nullable=True),
    sa.Column('is_discrepant', sa.Boolean(), nullable=False),
    sa.Column('discrepancy_type', sa.String(length=64), nullable=True),
    sa.Column('discrepancy_details', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliation_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_records_razorpay_payment_id'), ['razorpay_payment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_reconciliation_records_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('risk_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('ai_status', sa.String(length=32), nullable=False),
    sa.Column('ai_narrative', sa.Text(), nullable=True),
    sa.Column('ai_threat_vector', sa.String(length=64), nullable=True),
    sa.Column('ai_contributing_signals', sa.JSON(), nullable=True),
    sa.Column('ai_investigation_steps', sa.JSON(), nullable=True),
    sa.Column('ai_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_transaction_id'), ['transaction_id'], unique=True)

    op.create_table('rule_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('rule_name', sa.String(length=128), nullable=False),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.Column('score_impact', sa.Integer(), nullable=False),
    sa.Column('rule_metadata', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_evaluations_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_evaluations_transaction_id'))

    op.drop_table('rule_evaluations')
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessments_transaction_id'))

    op.drop_table('risk_assessments')
    with op.batch_alter_table('reconciliation_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_razorpay_payment_id'))

    op.drop_table('reconciliation_records')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_ref'))
        batch_op.drop_index(batch_op.f('ix_transactions_razorpay_payment_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_razorpay_order_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_ip_address'))
        batch_op.drop_index(batch_op.f('ix_transactions_customer_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_customer_email'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_card_fingerprint'))

    op.drop_table('transactions')
    with op.batch_alter_table('customers_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_blocklist_entity_value'))

    op.drop_table('customers_blocklist')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
